---
# roles/ansible-role-dotfiles/tasks/main.yml

- name: Ensure dotfiles repository is cloned locally
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
    force: true
  become: false

- name: Check for GNUmakefiles in dotfiles
  ansible.builtin.stat:
    path: "{{ dotfiles_repo_local_destination }}/{{ item }}/GNUmakefile"
  register: dotfiles_makefiles
  loop: "{{ dotfiles_files }}"
  loop_control:
    label: "{{ item }}"

- name: Run detected GNUmakefiles safely using Ansible make module
  ansible.builtin.make:
    chdir: "{{ dotfiles_repo_local_destination }}/{{ item.item }}"
    file: GNUmakefile
  loop: "{{ dotfiles_makefiles.results }}"
  loop_control:
    label: "{{ item.item }}"
  environment:
    PATH: "{{ dotfiles_brew_prefix }}/bin:{{ ansible_facts['user_dir'] }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  when: item.stat.exists
  become: false
  ignore_errors: true

- name: Check existing dotfile entries
  ansible.builtin.stat:
    path: "{{ dotfiles_home }}/{{ item }}"
  register: dotfiles_existing
  loop: "{{ dotfiles_files }}"
  loop_control:
    label: "{{ item }}"

- name: Remove old directory symlinks
  ansible.builtin.file:
    path: "{{ dotfiles_home }}/{{ item.item }}"
    state: absent
  loop: "{{ dotfiles_existing.results }}"
  loop_control:
    label: "{{ item.item }}"
  when:
    - item.stat.exists
    - item.stat.islnk
  become: false

- name: Find files in dotfile entries
  ansible.builtin.find:
    paths: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    file_type: file
    recurse: true
    hidden: true
  register: dotfiles_found
  loop: "{{ dotfiles_files }}"
  loop_control:
    label: "{{ item }}"

- name: Ensure target directories exist
  ansible.builtin.file:
    path: "{{ (dotfiles_home ~ '/' ~ item.0.item ~ '/' ~ (item.1.path | relpath(dotfiles_repo_local_destination ~ '/' ~ item.0.item))) | dirname }}"
    state: directory
    mode: "0755"
  loop: "{{ dotfiles_found.results | subelements('files') }}"
  loop_control:
    label: "{{ item.0.item }}/{{ item.1.path | basename }}"
  become: false

- name: Symlink dotfiles into home directory
  ansible.builtin.file:
    src: "{{ item.1.path }}"
    dest: "{{ dotfiles_home }}/{{ item.0.item }}/{{ item.1.path | relpath(dotfiles_repo_local_destination ~ '/' ~ item.0.item) }}"
    state: link
    force: true
  loop: "{{ dotfiles_found.results | subelements('files') }}"
  loop_control:
    label: "{{ item.0.item }}/{{ item.1.path | basename }}"
  become: false
